import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FileText, Briefcase, Home, Users, DollarSign, AlertCircle, Package, Star, Heart, CheckCircle, Plus, Minus } from 'lucide-react';

const Landing = () => {
  const navigate = useNavigate();
  const [openFaq, setOpenFaq] = useState(null);

  const handleCategories = [
    { icon: FileText, title: 'Demand letters', desc: 'Received a threatening legal letter? Know your rights and how to respond.', badge: 'Most common', badgeClass: 'badge-blue' },
    { icon: Briefcase, title: 'Employment disputes', desc: 'Wrongful termination, unpaid wages, discrimination, non-compete clauses.', badge: 'High risk', badgeClass: 'badge-red' },
    { icon: Home, title: 'Lease & tenant rights', desc: 'Illegal eviction, deposit disputes, unfair clauses, landlord violations.', badge: 'Very common', badgeClass: 'badge-green' },
    { icon: Users, title: 'Business contracts', desc: 'NDA, partnership agreements, service contracts, vendor disputes.', badge: 'B2B', badgeClass: 'badge-blue' },
    { icon: DollarSign, title: 'Debt collection', desc: "Collectors harassing you? Know your FDCPA rights and how to stop them.", badge: 'Urgent', badgeClass: 'badge-red' },
    { icon: AlertCircle, title: 'Consumer rights', desc: 'Scams, refund disputes, warranty claims, unfair business practices.', badge: 'Common', badgeClass: 'badge-green' },
    { icon: Package, title: 'Immigration documents', desc: 'Visa contracts, employment authorization, sponsor agreements review.', badge: 'Expats', badgeClass: 'badge-blue' },
    { icon: Star, title: 'Court notices', desc: 'Summons, small claims, subpoenas — understand what you received.', badge: 'Time-sensitive', badgeClass: 'badge-red' },
    { icon: Heart, title: 'Divorce & family law', desc: 'Separation agreements, custody basics, asset division overview.', badge: 'Sensitive', badgeClass: 'badge-gray' },
  ];

  const lawyers = [
    { name: 'Sarah Mitchell, Esq.', specialty: 'Employment Law', bar: 'New York Bar', years: 12, tags: ['Wrongful termination', 'Discrimination'], rating: 5.0, sessions: 214, status: 'now', photo: 'https://images.unsplash.com/photo-1585240975858-7264fd020798?w=200&h=200&fit=crop' },
    { name: 'James Carter, Esq.', specialty: 'Contract Law', bar: 'California Bar', years: 9, tags: ['Business disputes', 'NDA'], rating: 4.9, sessions: 187, status: '8 min', photo: 'https://images.unsplash.com/photo-1644268756851-3f69ffb9553f?w=200&h=200&fit=crop' },
    { name: 'Diana Torres, Esq.', specialty: 'Tenant Rights', bar: 'Texas Bar', years: 7, tags: ['Lease disputes', 'Eviction'], rating: 4.9, sessions: 156, status: '22 min', photo: 'https://images.unsplash.com/photo-1685760259914-ee8d2c92d2e0?w=200&h=200&fit=crop' },
  ];

  const reviews = [
    { text: '"I got a demand letter and panicked. Jasper told me my risk was 78/100 and exactly what to do. The attorney call saved me from a huge mistake."', name: 'Michael R.', loc: 'New York, NY' },
    { text: '"The attorney already knew my entire case before we spoke. Best $149 I ever spent. Would have paid $2,000 at a regular firm."', name: 'Jennifer L.', loc: 'Austin, TX' },
    { text: '"My landlord sent an illegal eviction notice. Jasper caught it instantly. My score dropped from 71 to 14 after I sent the response it helped me draft."', name: 'Carlos M.', loc: 'Miami, FL' },
  ];

  const faqs = [
    { q: 'Is Jasper giving me real legal advice?', a: 'Jasper provides legal information and document analysis — not legal advice. When you need actual legal advice, Jasper connects you to a licensed attorney.' },
    { q: 'Is my document secure?', a: 'All documents are encrypted with 256-bit encryption in transit and at rest. We never share your documents with third parties. You can delete your data anytime.' },
    { q: 'Who are the attorneys on Jasper?', a: 'All attorneys are independently licensed in their US states, with a minimum of 5 years of experience, and go through a rigorous vetting process before joining Jasper.' },
    { q: 'What if I need a lawyer in court?', a: 'Jasper is designed for advice and document analysis — not court representation. Our attorneys can advise you and refer you to the right specialist if needed.' },
    { q: 'How accurate is the Risk Score?', a: 'The Risk Score is generated by AI trained on thousands of legal documents and validated by licensed attorneys. It is a guidance tool to help you understand urgency and complexity.' },
    { q: 'Can I cancel my subscription anytime?', a: 'Yes. Cancel anytime with one click. No questions asked, no cancellation fees. Your case files remain accessible until the end of your billing period.' },
  ];

  return (
    <div className="min-h-screen bg-white" style={{ fontFamily: 'Inter, sans-serif' }}>
      {/* Nav */}
      <nav className="fixed top-0 left-0 right-0 bg-white/95 backdrop-blur-sm border-b border-[#ebebeb] z-50">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="text-2xl font-bold text-[#1a56db]" style={{ fontFamily: 'Outfit, sans-serif' }}>Jasper</div>
          <div className="hidden md:flex items-center gap-6 text-sm text-[#555]">
            <a href="#how" className="hover:text-[#1a56db]">How it works</a>
            <a href="#attorneys" className="hover:text-[#1a56db]">Attorneys</a>
            <a href="#pricing" className="hover:text-[#1a56db]">Pricing</a>
            <a href="#faq" className="hover:text-[#1a56db]">FAQ</a>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={() => navigate('/login')} className="text-sm text-[#555] hover:text-[#1a56db]" data-testid="nav-login-btn">Sign in</button>
            <button onClick={() => navigate('/signup')} className="px-4 py-2 bg-[#1a56db] text-white text-sm font-medium rounded-full hover:bg-[#1546b3] transition-colors" data-testid="nav-signup-btn">Get started</button>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-28 pb-16 px-6">
        <div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-12 items-center">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-[#eff6ff] text-[#1a56db] rounded-full text-xs font-medium mb-6">
              <span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>
              Trusted by 12,000+ Americans
            </div>
            <h1 className="text-4xl md:text-5xl font-bold text-[#111] leading-tight mb-5" style={{ fontFamily: 'Outfit, sans-serif' }}>
              Your lawyer,<br/>without the<br/><em className="not-italic text-[#1a56db]">lawyer fees.</em>
            </h1>
            <p className="text-[#555] text-base leading-relaxed mb-6">
              Got a legal problem? Upload your document. Jasper analyzes your risk in 60 seconds, tells you <strong>exactly what to do</strong> — and connects you to a real attorney only when you need one.
            </p>
            <div className="flex flex-wrap gap-3 mb-4">
              <button onClick={() => navigate('/signup')} className="px-6 py-3 bg-[#1a56db] text-white text-sm font-medium rounded-full hover:bg-[#1546b3] transition-colors" data-testid="hero-cta-btn">
                Analyze my document — free
              </button>
              <button onClick={() => navigate('/lawyers')} className="px-6 py-3 bg-white text-[#1a56db] text-sm font-medium rounded-full border border-[#1a56db] hover:bg-[#eff6ff] transition-colors">
                Talk to a lawyer now
              </button>
            </div>
            <p className="text-xs text-[#999]">No credit card · 60 seconds · Licensed US attorneys on demand</p>
          </div>
          <div className="relative">
            <div className="bg-gradient-to-br from-[#eff6ff] to-[#dbeafe] rounded-3xl p-8 relative">
              <div className="w-24 h-24 rounded-full bg-[#1a56db] mx-auto mb-4 flex items-center justify-center">
                <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.5"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
              </div>
              <div className="absolute top-4 right-4 px-3 py-1.5 bg-white rounded-full shadow-sm text-xs font-medium flex items-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-[#22c55e] animate-pulse"></span>
                3 attorneys available now
              </div>
              <div className="absolute -bottom-4 -left-4 bg-white rounded-xl shadow-lg p-4 w-52">
                <div className="text-[10px] text-[#999] uppercase tracking-wide mb-1">Your Risk Score</div>
                <div className="text-2xl font-bold text-[#dc2626]">78 / 100</div>
                <div className="h-1.5 bg-[#fee2e2] rounded-full mt-2 mb-2">
                  <div className="h-full w-[78%] bg-[#dc2626] rounded-full"></div>
                </div>
                <div className="flex items-center gap-1 text-xs text-[#dc2626]">
                  <span className="w-1.5 h-1.5 rounded-full bg-[#dc2626]"></span>
                  Act within 7 days
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Bar */}
      <div className="bg-[#f8f8f8] py-6 border-y border-[#ebebeb]">
        <div className="max-w-5xl mx-auto px-6 grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
          <div><div className="text-2xl font-bold text-[#111]">47,284</div><div className="text-xs text-[#999]">Documents analyzed</div></div>
          <div><div className="text-2xl font-bold text-[#111]">12,431</div><div className="text-xs text-[#999]">Americans protected</div></div>
          <div><div className="text-2xl font-bold text-[#111]">$8.2M</div><div className="text-xs text-[#999]">Legal fees saved</div></div>
          <div><div className="text-2xl font-bold text-[#111]">4.9/5</div><div className="text-xs text-[#999]">Average rating</div></div>
        </div>
      </div>

      {/* Trust Bar */}
      <div className="py-4 border-b border-[#ebebeb]">
        <div className="max-w-5xl mx-auto px-6 flex flex-wrap items-center justify-center gap-6 text-xs text-[#555]">
          {['Licensed US attorneys', 'Results in 60 seconds', '256-bit encryption', 'Attorney-reviewed AI', 'No hidden fees'].map((item) => (
            <div key={item} className="flex items-center gap-2">
              <div className="w-4 h-4 rounded-full bg-[#eff6ff] flex items-center justify-center">
                <CheckCircle size={10} className="text-[#1a56db]" />
              </div>
              {item}
            </div>
          ))}
        </div>
      </div>

      {/* Press Bar */}
      <div className="py-6 bg-[#fafafa]">
        <div className="max-w-5xl mx-auto px-6 flex items-center justify-center gap-8">
          <span className="text-xs text-[#999]">As seen in</span>
          {['FORBES', 'TechCrunch', 'ABA Journal', 'WIRED', 'Business Insider'].map((logo) => (
            <span key={logo} className="text-sm font-semibold text-[#ccc]">{logo}</span>
          ))}
        </div>
      </div>

      {/* What Jasper Handles */}
      <section className="py-16 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-10">
            <div className="text-[10px] uppercase tracking-wider text-[#1a56db] font-semibold mb-2">What Jasper handles</div>
            <h2 className="text-2xl md:text-3xl font-bold text-[#111] mb-3" style={{ fontFamily: 'Outfit, sans-serif' }}>Whatever your legal problem — Jasper handles it.</h2>
            <p className="text-sm text-[#666] max-w-xl mx-auto">From demand letters to employment disputes, lease issues to business contracts — Jasper covers every common legal situation Americans face every day.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {handleCategories.map((cat, i) => (
              <div key={i} className="card p-4 hover:shadow-md transition-shadow">
                <div className="w-9 h-9 rounded-lg bg-[#eff6ff] flex items-center justify-center mb-3">
                  <cat.icon size={16} className="text-[#1a56db]" />
                </div>
                <div className="text-sm font-semibold text-[#111] mb-1">{cat.title}</div>
                <div className="text-xs text-[#666] mb-2 leading-relaxed">{cat.desc}</div>
                <span className={`badge ${cat.badgeClass} text-[10px]`}>{cat.badge}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* The Problem */}
      <section className="py-16 px-6 bg-[#f8f8f8]">
        <div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-10 items-center">
          <div>
            <div className="text-[10px] uppercase tracking-wider text-[#1a56db] font-semibold mb-2">The problem</div>
            <h2 className="text-2xl md:text-3xl font-bold text-[#111] mb-4" style={{ fontFamily: 'Outfit, sans-serif' }}>Legal help used to cost $500 just to ask a question.</h2>
            <p className="text-sm text-[#555] leading-relaxed mb-4">You received a demand letter. A contract you don't understand. An eviction notice. You're stressed — and a real lawyer costs $500/hr just to pick up the phone. Jasper changes that.</p>
            <div className="space-y-2">
              {['Upload your document in seconds', 'Get your Risk Score instantly', 'Know exactly what to do next', 'Talk to a real lawyer for $149 — not $500/hr'].map((item) => (
                <div key={item} className="flex items-center gap-2 text-sm text-[#444]">
                  <div className="w-4 h-4 rounded-full bg-[#eff6ff] flex items-center justify-center flex-shrink-0">
                    <CheckCircle size={10} className="text-[#1a56db]" />
                  </div>
                  {item}
                </div>
              ))}
            </div>
          </div>
          <div className="card p-5">
            <div className="bg-[#eff6ff] rounded-lg p-4 mb-4 flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-[#dbeafe] flex items-center justify-center">
                <FileText size={14} className="text-[#1a56db]" />
              </div>
              <div>
                <div className="text-sm font-medium text-[#111]">demand_letter.pdf uploaded</div>
                <div className="text-xs text-[#1a56db]">Analyzing in 60 seconds...</div>
              </div>
            </div>
            <div className="bg-white border border-[#ebebeb] rounded-xl p-4">
              <div className="text-[10px] text-[#999] uppercase tracking-wide mb-1">Jasper Risk Score</div>
              <div className="text-xl font-bold text-[#dc2626] mb-2">78 / 100 — High Risk</div>
              <div className="h-2 bg-[#fee2e2] rounded-full mb-3">
                <div className="h-full w-[78%] bg-[#dc2626] rounded-full"></div>
              </div>
              <div className="text-xs text-[#dc2626] font-medium mb-3 flex items-center gap-1">
                <span>⚡</span> Respond within 10 days
              </div>
              <div className="space-y-1.5">
                {['Clause 3.2 legally enforceable', 'Financial exposure up to $8,400', 'Strong case for negotiation'].map((tag) => (
                  <div key={tag} className="flex items-center gap-2 text-xs text-[#444]">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#dc2626]"></span>
                    {tag}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* How it Works */}
      <section className="py-16 px-6" id="how">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-10">
            <div className="text-[10px] uppercase tracking-wider text-[#1a56db] font-semibold mb-2">How it works</div>
            <h2 className="text-2xl md:text-3xl font-bold text-[#111]" style={{ fontFamily: 'Outfit, sans-serif' }}>From confused to confident — in 4 steps</h2>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {[
              { num: 1, title: 'Upload your document', desc: 'Any format. Demand letter, contract, court notice. Takes 10 seconds.' },
              { num: 2, title: 'Get your Risk Score', desc: 'Score from 0–100. Plain English. No jargon. In 60 seconds.' },
              { num: 3, title: 'Your case stays alive', desc: 'Add docs as they arrive. Score updates. Next step always clear.' },
              { num: 4, title: 'Talk to a lawyer', desc: '$149 for 30 min. Attorney pre-briefed. No time wasted.' }
            ].map((step) => (
              <div key={step.num} className="text-center">
                <div className="w-10 h-10 rounded-full bg-[#1a56db] text-white font-bold flex items-center justify-center mx-auto mb-3">{step.num}</div>
                <div className="text-sm font-semibold text-[#111] mb-1">{step.title}</div>
                <div className="text-xs text-[#666]">{step.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Talk to a Lawyer Now */}
      <section className="py-16 px-6 bg-[#1a56db]" id="lawyers-now">
        <div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-10 items-center">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-white/20 text-white rounded-full text-xs font-medium mb-4">
              <span className="w-2 h-2 rounded-full bg-[#22c55e] animate-pulse"></span>
              Attorneys available right now
            </div>
            <h2 className="text-2xl md:text-3xl font-bold text-white mb-4" style={{ fontFamily: 'Outfit, sans-serif' }}>Talk to a real lawyer.<br/>By video. Right now.</h2>
            <p className="text-sm text-[#93c5fd] leading-relaxed mb-6">Don't wait days for an appointment. Connect to a licensed US attorney in minutes — pre-briefed with your full case. 30 minutes, flat fee, no surprises.</p>
            <button onClick={() => navigate('/lawyers')} className="px-6 py-3 bg-white text-[#1a56db] text-sm font-medium rounded-full hover:bg-[#f8f8f8] transition-colors">
              Book a video call — $149
            </button>
            <p className="text-xs text-[#93c5fd] mt-3">Available same day · Any US state · Licensed & vetted</p>
          </div>
          <div className="space-y-3">
            {lawyers.map((lawyer, i) => (
              <div key={i} className="bg-white rounded-xl p-4 flex items-center gap-4">
                <div className="w-12 h-12 rounded-full bg-[#eff6ff] flex items-center justify-center flex-shrink-0 overflow-hidden">
                  {lawyer.photo ? (
                    <img src={lawyer.photo} alt={lawyer.name} className="w-full h-full object-cover" />
                  ) : (
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#1a56db" strokeWidth="1.5"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                  )}
                </div>
                <div className="flex-1">
                  <div className="text-sm font-semibold text-[#111]">{lawyer.name}</div>
                  <div className="text-xs text-[#666]">{lawyer.specialty} · {lawyer.bar.split(' ')[0]} Bar</div>
                  <div className="flex items-center gap-1 text-xs mt-1">
                    <span className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: lawyer.status === 'now' ? '#22c55e' : '#f59e0b' }}></span>
                    <span style={{ color: lawyer.status === 'now' ? '#16a34a' : '#d97706', fontWeight: 500 }}>
                      {lawyer.status === 'now' ? 'Available now' : `Available in ${lawyer.status}`}
                    </span>
                  </div>
                </div>
                <button onClick={() => navigate(`/lawyers/book?lawyer=lawyer_${lawyer.name.split(' ')[0].toLowerCase()}`)} className="px-4 py-2 bg-[#1a56db] text-white text-xs font-medium rounded-full hover:bg-[#1546b3]">Book call</button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Our Attorneys */}
      <section className="py-16 px-6 bg-[#f8f8f8]" id="attorneys">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-10">
            <div className="text-[10px] uppercase tracking-wider text-[#1a56db] font-semibold mb-2">Our attorneys</div>
            <h2 className="text-2xl md:text-3xl font-bold text-[#111]" style={{ fontFamily: 'Outfit, sans-serif' }}>Real lawyers. Vetted. Ready.</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {lawyers.map((lawyer, i) => (
              <div key={i} className="card overflow-hidden">
                <div className="h-28 bg-gradient-to-br from-[#eff6ff] to-[#dbeafe] flex items-center justify-center">
                  {lawyer.photo ? (
                    <img src={lawyer.photo} alt={lawyer.name} className="w-full h-full object-cover" />
                  ) : (
                    <div className="w-16 h-16 rounded-full bg-[#1a56db] flex items-center justify-center">
                      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.5"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                    </div>
                  )}
                </div>
                <div className="p-4">
                  <div className="text-sm font-semibold text-[#111]">{lawyer.name}</div>
                  <div className="text-xs text-[#666] mb-2">{lawyer.specialty} · {lawyer.bar} · {lawyer.years} yrs</div>
                  <div className="flex flex-wrap gap-1 mb-2">
                    {lawyer.tags.map((tag, j) => <span key={j} className="badge badge-blue text-[10px]">{tag}</span>)}
                  </div>
                  <div className="flex items-center gap-1 text-xs">
                    <span className="text-[#f59e0b]">★★★★★</span>
                    <span className="text-[#111] font-medium">{lawyer.rating}</span>
                    <span className="text-[#999]">· {lawyer.sessions} sessions</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-16 px-6" id="pricing">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-10">
            <div className="text-[10px] uppercase tracking-wider text-[#1a56db] font-semibold mb-2">Pricing</div>
            <h2 className="text-2xl md:text-3xl font-bold text-[#111]" style={{ fontFamily: 'Outfit, sans-serif' }}>Lawyer-level help. Not lawyer-level prices.</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-6 max-w-4xl mx-auto">
            {/* Free */}
            <div className="card p-6">
              <div className="text-lg font-semibold text-[#111] mb-1">Free</div>
              <div className="text-3xl font-bold text-[#111]">$0</div>
              <div className="text-xs text-[#999] mb-4">forever</div>
              <button onClick={() => navigate('/signup')} className="w-full py-2.5 border border-[#1a56db] text-[#1a56db] text-sm font-medium rounded-full hover:bg-[#eff6ff] mb-4">Start for free</button>
              <div className="space-y-2 text-xs text-[#444]">
                <div className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>1 free document analysis</div>
                <div className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>Risk Score overview</div>
                <div className="flex items-center gap-2 text-[#ccc]"><span className="w-1.5 h-1.5 rounded-full bg-[#ccc]"></span>Full risk report</div>
                <div className="flex items-center gap-2 text-[#ccc]"><span className="w-1.5 h-1.5 rounded-full bg-[#ccc]"></span>Live case file</div>
                <div className="flex items-center gap-2 text-[#ccc]"><span className="w-1.5 h-1.5 rounded-full bg-[#ccc]"></span>Attorney access</div>
              </div>
            </div>
            {/* Pro */}
            <div className="card p-6 border-2 border-[#1a56db] relative">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-1 bg-[#1a56db] text-white text-[10px] font-medium rounded-full">Most popular</div>
              <div className="text-lg font-semibold text-[#111] mb-1">Pro</div>
              <div className="text-3xl font-bold text-[#111]">$69</div>
              <div className="text-xs text-[#999] mb-4">per month</div>
              <button onClick={() => navigate('/signup')} className="w-full py-2.5 bg-[#1a56db] text-white text-sm font-medium rounded-full hover:bg-[#1546b3] mb-4">Get started</button>
              <div className="space-y-2 text-xs text-[#444]">
                <div className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>Unlimited analyses</div>
                <div className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>Full risk reports</div>
                <div className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>Live case file</div>
                <div className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>Dynamic Risk Score</div>
                <div className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>Priority support</div>
              </div>
            </div>
            {/* Attorney */}
            <div className="card p-6">
              <div className="text-lg font-semibold text-[#111] mb-1">Attorney call</div>
              <div className="text-3xl font-bold text-[#111]">$149</div>
              <div className="text-xs text-[#999] mb-4">per session</div>
              <button onClick={() => navigate('/lawyers')} className="w-full py-2.5 border border-[#1a56db] text-[#1a56db] text-sm font-medium rounded-full hover:bg-[#eff6ff] mb-4">Book a call</button>
              <div className="space-y-2 text-xs text-[#444]">
                <div className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>30-min video call</div>
                <div className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>Licensed US attorney</div>
                <div className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>Pre-briefed by Jasper AI</div>
                <div className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>Written follow-up</div>
                <div className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[#1a56db]"></span>Same-day availability</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Reviews */}
      <section className="py-16 px-6 bg-[#f8f8f8]">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-10">
            <div className="text-[10px] uppercase tracking-wider text-[#1a56db] font-semibold mb-2">Reviews</div>
            <h2 className="text-2xl md:text-3xl font-bold text-[#111]" style={{ fontFamily: 'Outfit, sans-serif' }}>Real people. Real results.</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {reviews.map((review, i) => (
              <div key={i} className="card p-5">
                <div className="text-[#f59e0b] mb-3">★★★★★</div>
                <div className="text-sm text-[#444] leading-relaxed mb-4">{review.text}</div>
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-full bg-[#dbeafe]"></div>
                  <div>
                    <div className="text-sm font-medium text-[#111]">{review.name}</div>
                    <div className="text-xs text-[#999]">{review.loc}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-16 px-6" id="faq">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-10">
            <div className="text-[10px] uppercase tracking-wider text-[#1a56db] font-semibold mb-2">FAQ</div>
            <h2 className="text-2xl md:text-3xl font-bold text-[#111]" style={{ fontFamily: 'Outfit, sans-serif' }}>Questions you probably have</h2>
          </div>
          <div className="space-y-3">
            {faqs.map((faq, i) => (
              <div key={i} className="card overflow-hidden">
                <button 
                  className="w-full p-4 flex items-center justify-between text-left"
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                >
                  <span className="text-sm font-medium text-[#111]">{faq.q}</span>
                  {openFaq === i ? <Minus size={16} className="text-[#1a56db]" /> : <Plus size={16} className="text-[#999]" />}
                </button>
                {openFaq === i && (
                  <div className="px-4 pb-4 text-sm text-[#666] leading-relaxed">{faq.a}</div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 px-6 bg-[#1a56db] text-center">
        <h2 className="text-3xl md:text-4xl font-bold text-white mb-4" style={{ fontFamily: 'Outfit, sans-serif' }}>Your lawyer, without<br/>the lawyer fees.</h2>
        <p className="text-[#93c5fd] mb-8">Join 12,000+ Americans who use Jasper to protect themselves — for less.</p>
        <button onClick={() => navigate('/signup')} className="px-8 py-3.5 bg-white text-[#1a56db] font-medium rounded-full hover:bg-[#f8f8f8] transition-colors" data-testid="final-cta-btn">
          Analyze my document — it's free
        </button>
      </section>

      {/* Footer */}
      <footer className="py-8 px-6 bg-[#111] text-center">
        <div className="text-xl font-bold text-white mb-4" style={{ fontFamily: 'Outfit, sans-serif' }}>Jasper</div>
        <p className="text-xs text-[#666] max-w-2xl mx-auto">
          Jasper provides legal information and document analysis, not legal advice. Attorney consultations are conducted by independent, licensed legal professionals. Jasper does not create an attorney-client relationship. · © 2026 Jasper Inc.
        </p>
      </footer>
    </div>
  );
};

export default Landing;
